apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hungnm-de000155-prod-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/manhhung610/vti-eks-mock.git
    targetRevision: main
    path: gitops/applications/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mock-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
